### ISSUE TITLE
Websockets?

### ISSUE THREAD

**Issue by arschles** [arschles/go-in-5-minutes#10]
maybe a simple example on how and why to use websockets? not much more ideas around this yet...

**Comment by carlisia** [comment]
:+1:

**Comment by gotjosh** [comment]
:+1:

**Comment by eduardonunesp** [comment]
:+1:

**Comment by garyburd** [comment]
Feel free to use [my example](http://gary.burd.info/go-websocket-chat) in a screencast.

**Comment by marcosinger** [comment]
:+1:

**Comment by surfeurX** [comment]
:+1:

**Comment by arschles** [comment]
thanks @garyburd!
