### ISSUE TITLE
Consuming a given REST API in Go

### ISSUE THREAD

**Issue by Comradin** [arschles/go-in-5-minutes#109]
Hello,

Episode 1 and 11 are about "Building a RESTful API in Go Using Only the Standard Library" and "Structuring JSON APIs in Go". Its about the server part of an API, but what about designing a client to consume such a service with a command line tool?

**Comment by arschles** [comment]
@Comradin at long last, I did a screencast for this! Check out https://www.goin5minutes.com/screencast/episode_26_writing_rest_clients/ and let me know what you think.

And thanks for waiting ~3 years 😁
