### ISSUE TITLE
Build an application that sorts a Github repos issues by reactions

### ISSUE THREAD

**Issue by jasonmccallister** [arschles/go-in-5-minutes#118]
This is an idea that I thought of while looking through your issues... It would be great if there was a small application in Go that could organize a repos issues by the type and number of reactions to a request for screencast...

Although the functionality does exist here: https://cl.ly/0F280W1X0A0J

**Comment by arschles** [comment]
Thanks for the idea @themccallister! I'm starting GIFM up again soon, so I'll get to doing this cast as soon as I can. I'll mention you here when I do.
