### ISSUE TITLE
Building a command line tool

### ISSUE THREAD

**Issue by themccallister** [arschles/go-in-5-minutes#119]
Would be great to see a command line tool built in Go. I know its a little trivial, but would be a great screencast idea!

**Comment by arschles** [comment]
Thanks for this @themccallister. I'm a big fan of [Cobra](https://github.com/spf13/cobra) so I'll do a cast on that package and update here when it's out.

**Comment by arschles** [comment]
@themccallister this screencast is now up on the website. Cheers!

https://www.goin5minutes.com/screencast/episode_18_cli_with_cobra/
