### ISSUE TITLE
Clarification - Episode 11 - Structuring JSON APIs in Go

### ISSUE THREAD

**Issue by rssenar** [arschles/go-in-5-minutes#122]
Hi Aaron, not sure what this line is doing...

**app, ok := m.(*App)**

from Episode 11 - Structuring JSON APIs in Go.  Still new to go and trying to learn all the different patterns.  full code below.

// Set is the Model interface implementation
func (a *App) Set(m Model) error {
  app, ok := m.(*App)
  if !ok {
    return fmt.Errorf("given model %+v was not an *App", m)
  }
  *a = *app
  return nil
}

Would you mind clarifying? Thanks

**Comment by arschles** [comment]
hi @rssenar - the code you see (copied below):

```go
// Set is the Model interface implementation
func (a *App) Set(m Model) error {
    app, ok := m.(*App)
    if !ok {
        return fmt.Errorf("given model %+v was not an *App", m)
    }
    *a = *app
    return nil
}
```

is doing this:

- First, it's trying to _type assert_ the incoming `Model` into a more specific type, an `App`. Type assertion is similar to casting in other languages, except in Go you have to go from an `interface` to a concrete type (in this case, a `struct`)
- The second return value, `ok`, is a boolean that indicates if the type assertion worked. It won't if `m` -- which is an `interface` -- is not actually an `App` under the hood. The `if` is checking if the assertion worked
- The lines after the `if` are fairly standard. First we assign ourselves to the new `App`. The `a` variable is called a _receiver_ in Go. In other languages, it would be similar to the special `this` variable inside a `class`. But in Go, we can actually use this as a variable. Here we are doing that, and assigning it to a new value

I hope this explanation helps! I'm going to close this issue. Please mention me in this issue or open a new one if you have additional questions.

**Comment by arschles** [comment]
I'm going to close this issue. @rssenar please let me know if you have more questions by opening a new issue. Thanks!
