### ISSUE TITLE
Consuming unknown JSON input

### ISSUE THREAD

**Issue by tmcarr** [arschles/go-in-5-minutes#125]
It would be nice to go over how one can consume json with some number of unknown fields.

I have a case where I need to consume a file with a certain set of known fields that I can make structs for, but some of those fields can contain any number of user entered fields and values and I'm unsure of how to handle this. I've seen some info in the godocs about setting the type to interface{} and then using a switch case to detect the type of the fields inside, but its pretty unclear. 

Thanks!
Travis

**Comment by tmcarr** [comment]
Also, I cant seem to add the label you request in the README.

**Comment by arschles** [comment]
Hi @tmcarr - sorry for the delay, I'm starting up GIFM again after a long time off, and I like this idea. I have a few ideas on casts for this, so I'll present at least one of them as soon as I can, and I'll update here.

Also, I added the label for you. I'm gonna need to update the README to not require folks to add the label - GH doesn't allow it 😄

**Comment by arschles** [comment]
@tmcarr check out episode 19 - this is done
