### ISSUE TITLE
Go templates

### ISSUE THREAD

**Issue by arschles** [arschles/go-in-5-minutes#13]
not sure what specifically, but there's a lot to choose from here

**Comment by lcowell** [comment]
:+1:

**Comment by nikovacevic** [comment]
+1

Specifically, for web applications it would be helpful to see an approach for composition of templates (layout, view, partials, etc.). I've heard that [flosch/pongo2](https://github.com/flosch/pongo) is worth using, but I haven't had a chance to check it out in-depth.

Hope that helps. Thanks!

**Comment by arschles** [comment]
@nikovacevic I've covered templates briefly in #30 (screencast still uploading as of this writing), but I'd be ok doing another cast to focus just on templates

**Comment by gotoddorg** [comment]
:+1: - focus on templates

**Comment by arschles** [comment]
Finished and up at https://github.com/arschles/go-in-5-minutes/tree/master/episode14

**Comment by arschles** [comment]
Also, this comes with an extended screencast for a fee. 1 hr of additional detail and patterns on the package. Buy it here: https://gumroad.com/l/gifm-x-14
