### ISSUE TITLE
what packages & frameworks are most used (or should be used ) for the Real life development in Golang 

### ISSUE THREAD

**Issue by NaderJS** [arschles/go-in-5-minutes#148]
even if this language is 9 years old , it has many frameworks and packages outside the standard library so which are most used in the golang market ? which should be used ?and is it better to use just the standard library packages as much as possible?

**Comment by arschles** [comment]
I just did a screencast with a bunch of packages/frameworks that I like. I'm gonna PR it soon, but leaving these links here for now:

- https://github.com/spf13/cobra
- https://github.com/pborman/uuid
- https://github.com/technosophos/moniker
- https://github.com/gobuffalo/buffalo
- https://github.com/gobuffalo/plush
- https://github.com/gobuffalo/pop
- https://github.com/BurntSushi/toml
- https://github.com/dgrijalva/jwt-go
- https://github.com/go-redis/redis
- https://github.com/gorilla/websocket
- https://github.com/stretchr/testify

**Comment by arschles** [comment]
@NaderJS I just posted a 20+ minute screencast with a bunch of packages that can help you!

https://www.goin5minutes.com/screencast/episode_23_popular_packages/
