### ISSUE TITLE
Gorilla Mux

### ISSUE THREAD

**Issue by arschles** [arschles/go-in-5-minutes#18]
show some common patterns, etc...

**Comment by jcmartins** [comment]
Maybe a Gorilla vs httprouter? (https://github.com/julienschmidt/httprouter)

**Comment by arschles** [comment]
@jcmartins how about 2 screencasts covering each one instead?

**Comment by gotjosh** [comment]
:+1:

**Comment by vdemario** [comment]
:+1:

**Comment by surfeurX** [comment]
:+1:
