### ISSUE TITLE
how structured your Web application

### ISSUE THREAD

**Issue by Antse** [arschles/go-in-5-minutes#24]

**Comment by arschles** [comment]
:+1:

**Comment by digitalcraftsman** [comment]
:+1:

**Comment by nikovacevic** [comment]
+1

**Comment by arschles** [comment]
@Antse @nikovacevic @digitalcraftsman any specific kinds of web applications you're thinking of? For example: CMS, a one-page application, CRUD database application, etc...?

**Comment by Antse** [comment]
We can imagine something like CRUD application would be fine.

Something like how start the project, how structure it (best practices, better efficiency )

**Comment by digitalcraftsman** [comment]
I agree with @Antse that a CRUD application would fit best, since it's the foundation of a more advanced CMS. And aren't one-page applications mostly used with restful APIS, that you already covered in episode 1?

**Comment by ab27** [comment]
:+1:

**Comment by johnzan** [comment]
With a mongodb backend would be great, using one of the free online ones such as MongoLab.
Thx.

**Comment by carlisia** [comment]
:+1:

**Comment by lcowell** [comment]
:+1:

**Comment by Antse** [comment]
@arschles 
We can imagine a stack like angular + golang + mongo ?

**Comment by nikovacevic** [comment]
@Antse That would be fantastic. +1

**Comment by arschles** [comment]
@digitalcraftsman I was imagining that the single page app example could be a more holistic view of how the app's folder structure is laid out, how templates are rendered, how handlers are registered, etc...

that type of example dove-tails well with @Antse and @johnzan's suggestions of having an angular/go/mongoDB stack.

anyway, this got a ton of votes, so I'm gonna be releasing it very soon!

**Comment by digitalcraftsman** [comment]
@arschles You're right. And CRUD will be covered to with the use of MongoDB.

**Comment by digitalcraftsman** [comment]
Last but not least thanks for sharing your time and experience with us. Keep going in the hope that your audience will grow further.

**Comment by arschles** [comment]
@digitalcraftsman you're welcome! I'm very motivated by all the feedback, good or bad, so please keep it coming. 

also, I have some exciting things planned

**Comment by Antse** [comment]
thanks a lot great Tutorial

**Comment by arschles** [comment]
:+1: @Antse
