### ISSUE TITLE
Data race in episode4

### ISSUE THREAD

**Issue by garyburd** [arschles/go-in-5-minutes#27]
[Range over the connection map](https://github.com/arschles/go-in-5-minutes/blob/2c9c7d1bf94b231dadf19e9ff830adb010f8aeac/episode4/hub.go#L33) can execute concurrently with modifications to the map in [addConnection](https://github.com/arschles/go-in-5-minutes/blob/2c9c7d1bf94b231dadf19e9ff830adb010f8aeac/episode4/hub.go#L51) and [removeConnection](https://github.com/arschles/go-in-5-minutes/blob/2c9c7d1bf94b231dadf19e9ff830adb010f8aeac/episode4/hub.go#L58).

**Comment by arschles** [comment]
thanks @garyburd - fixed in #28
