### ISSUE TITLE
Episode pages embed wrong video

### ISSUE THREAD

**Issue by inkel** [arschles/go-in-5-minutes#36]
_EDIT: I've changed the name of the issue as I've found a similar one_

* In [Episode 0](http://www.goin5minutes.com/screencast/episode_0_writing_testable_code_and_fast_unit_tests_using_mocking/) the embedded video is [_Building Full Stack Web Applications in Go (Episode 5)_](https://www.youtube.com/watch?v=QvWUCYwmExE) instead.

* In [Episode 1](http://www.goin5minutes.com/screencast/episode_1_building_restful_api_using_only_std_lib/) the embedded video is [_Writing Webapps With Gorilla Mux (Episode 3)_](https://www.youtube.com/watch?v=6Pl5Xrrne2c) instead.

**Comment by inkel** [comment]
Sorry I didn't open a pull request, but I'm watching the videos ;)

**Comment by arschles** [comment]
no problem @inkel - I'll fix this afternoon
