### ISSUE TITLE
Covering the sql package

### ISSUE THREAD

**Issue by digitalcraftsman** [arschles/go-in-5-minutes#43]
Would it be possible to make a screencast about the [`database/sql`](https://godoc.org/database/sql) package? Relational databases are still widely used in applications.

**Comment by arschles** [comment]
yes, definitely

:+1:

**Comment by tcbtcb** [comment]
More more more, yes! A discussion of using either the SQL package or the (really badass) MongoDB driver would be great.

**Comment by arschles** [comment]
@tcbtcb I've created https://github.com/arschles/go-in-5-minutes/issues/62 to track the MongoDB driver work 👍
