### ISSUE TITLE
Example JSON API with proper separation of concerns. 

### ISSUE THREAD

**Issue by gotjosh** [arschles/go-in-5-minutes#5]
We all know the typical JSON API tutorial, but, I believe the "advance" approach where you showcase how the concepts of episode 0 are applied would be a great example!

**Comment by arschles** [comment]
@gotjosh Do you mean mocking out an external JSON API in a program?

**Comment by gotjosh** [comment]
No, i meant, using Business Objects to build an API. As in `UserCreator` which could receive the `DB` context, and a reference to an user to save it.

**Comment by arschles** [comment]
@gotjosh let me think on this, there's a lot of potential content here

**Comment by gotjosh** [comment]
I'm not much of an expert on Go but if you'd like/need any help I'b be more than willing!

**Comment by arschles** [comment]
thanks a ton @gotjosh - I may take you up on that when I develop code & outline for this one.

**Comment by vdemario** [comment]
:+1:

**Comment by carlisia** [comment]
:+1:

**Comment by arschles** [comment]
@gotjosh @vdemario @carlisia wondering if #24 (https://www.youtube.com/watch?v=QvWUCYwmExE) covered some of the topics here? I'm looking for drill down to specifics in this screencast

**Comment by carlisia** [comment]
@arschles I think so; it'll be good to see a deep dive on this for sure.

**Comment by vdemario** [comment]
I think so too.

**Comment by arschles** [comment]
I'm gonna start developing content for this topic soon, and I'll be mentioning everyone here in the PR. 

initial ideas for splitting this up, for my future reference:

1. mapping JSON request/response `struct`s to data storage "objects" (likely `struct`s)
2. dealing with a 'user' object or other authentication context when doing operations (probably some overlap with #15). includes translating some incoming token to a user (if OAuth, requires a DB operation)
3. separating, handlers ('business logic'), data object ('models') and database implementation (overlap with #43)

**Comment by carlisia** [comment]
:clap:
