### ISSUE TITLE
background jobs

### ISSUE THREAD

**Issue by cleesmith** [arschles/go-in-5-minutes#53]
I am new to Go, but I have been doing background jobs for years using both Ruby/Rails and Python/Flask with supporting software such as Redis, Resque, Sidekiq, APScheduler, and Celery. 
There just doesn't seem to be as much information for doing this in Go web apps.

Often in web apps there is a need to perform one or more tasks in the background, such as:
* long running reports which are emailed to user(s)
* creating PDF or Excel files
* alerting on various database changes (usually emailed)

Almost always a part of any web app:
* authenticating and authorizing users
* user session security: form submission authenticity, cross site scripting, and so on
* background job submission and scheduling (hourly, daily, weekly)

A screencast on any of the above would be great.

**Comment by arschles** [comment]
@cleesmith yep, I can put together a good background jobs tutorial.

the auth and security points will be covered in https://github.com/arschles/go-in-5-minutes/issues/49 and https://github.com/arschles/go-in-5-minutes/issues/15, respectively

**Comment by cleesmith** [comment]
thanks

**Comment by arschles** [comment]
@cleesmith makes sense, thanks for clarifying.

I'm planning to focus on encrypted password, session cookies and storing sessions in the database in #49. For this issue, I'll cover background jobs and leave the auth part for #49. Thanks again!

**Comment by cleesmith** [comment]
I'm looking forward to them ... thanks.
